# Generated by Django 3.1.4 on 2020-12-05 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mlalgorithmstatus',
            old_name='parent_endpoint',
            new_name='parent_mlalgorithm',
        ),
        migrations.RenameField(
            model_name='mlrequest',
            old_name='parent_endpoint',
            new_name='parent_mlalgorithm',
        ),
    ]
